SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION GETVALUE(Grade IN VARCHAR2)
RETURN NUMBER IS
BEGIN
	IF Grade='S' THEN
		RETURN 100;
	ELSIF Grade='A+' THEN
		RETURN 90;
	ELSIF Grade='A' THEN
		RETURN 80;
	ELSIF Grade='B+' THEN
		RETURN 70;
	ELSIF Grade='B' THEN
		RETURN 60;
	ELSIF Grade='C+' THEN
		RETURN 50;
	ELSIF Grade='C' THEN
		RETURN 40;
	ELSIF Grade='D' THEN
		RETURN 35;
	ELSIF Grade='F' THEN
		RETURN 0;
	END IF;
END GETVALUE;
/ 

CREATE TABLE STUDENTMARK(
	Name VARCHAR(20),
	KTUID VARCHAR(10),
	Semester VARCHAR(10),
	Sname VARCHAR(30),
	Scode VARCHAR(20),
	Credit NUMBER,
	Internal NUMBER,
	Grade VARCHAR(2)
	PRIMARY KEY(KTUID,Semester,Scode));

CREATE TABLE SGPACSE(
	KTUID VARCHAR(10),
	Semester VARCHAR(10),
	Sgpa FLOAT NOT NULL);

CREATE TABLE CGPACSE(
	KTUID VARCHAR(10),
	Cgpa FLOAT NOT NULL);

CREATE OR REPLACE TRIGGER Modified_Mark
BEFORE UPDATE OR INSERT ON STUDENTMARK
FOR EACH ROW

DECLARE
	CURSOR

BEGIN

END;
/

INSERT INTO STUDENTMARK VALUES('Naruto Uzumaki','KTE22CS024','S1','Chemistry','EST101',4,46,'S');
INSERT INTO STUDENTMARK VALUES('Naruto Uzumaki','KTE22CS024','S1','Graphics','EST102',4,45,'A+');
INSERT INTO STUDENTMARK VALUES('Naruto Uzumaki','KTE22CS024','S1','Mathematics','MAT101',4,46,'A');
INSERT INTO STUDENTMARK VALUES('Naruto Uzumaki','KTE22CS024','S2','Physics','EST201',4,46,'S');
INSERT INTO STUDENTMARK VALUES('Naruto Uzumaki','KTE22CS024','S2','Mechanics','EST202',4,45,'S');
INSERT INTO STUDENTMARK VALUES('Naruto Uzumaki','KTE22CS024','S2','Mathematics','MAT201',4,47,'A+');

SELECT * FROM STUDENTMARK;
SELECT * FROM SGPACSE;

DROP TABLE CGPACSE;
DROP TABLE SGPACSE;
DROP TABLE STUDENTMARK;
